import Head from "next/head";
import Sidebar from "../components/sidebar";
import Login from "../components/login";
import Feed from "../components/feed";
import Widgets from "../components/widgets";
import { getProviders, getSession, useSession } from "next-auth/react";
import Modal from "../components/modal";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modalAtom";

export default function Home({ trendingResults, followResults, providers }) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);

  if (!session) return <Login providers={providers} />;

  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] max-auto">
        <Sidebar />
        <Feed />
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />

        {isOpen && <Modal />}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://jsonkeeper.com/b/AAJO").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/8OSD").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}
